login:
  isRememberedPassword: true
  isRememberedUsername: true
  password: '123456'
  username: szx
user:
  token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTUzMTM4OTMsInVzZXJJZCI6MH0.QSEOLgiW1HaPjIH_wm8rJoe8flxS-QhnlmZ6LaX9eec
