login:
  isRememberedPassword: true
  isRememberedUsername: true
  password: '123456'
  username: szx
user:
  token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDY3MTk2NDQsInVzZXJJZCI6MH0.LA21ovfCAgf84fBeQjqqzHz38dINVpbNutv4S4TdOOQ
