login:
  isRememberedPassword: true
  isRememberedUsername: true
  password: '123456'
  username: szx
user:
  token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTM0OTc4NjYsInVzZXJJZCI6MH0.kFE_lAdEiItewcc8GMkR3HJMlQ8E05dhTsqPWEyc5rI
