login:
  isRememberedPassword: true
  isRememberedUsername: true
  password: '123456'
  username: szx
user:
  token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTI4MDU2MTksInVzZXJJZCI6MH0.xaWsftudhWkDL2psJweVZ8dorX1-qxFgfveHZaV4tjQ
